# Generated by Django 2.2.4 on 2020-08-20 02:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='switch_point',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Silakan pilih "situasi" Anda'),
        ),
    ]
