# Generated by Django 2.2.4 on 2020-08-26 06:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_intro', '0002_auto_20200820_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comprehend_correct',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
