# Generated by Django 2.2.4 on 2020-09-25 03:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_intro', '0003_auto_20200826_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comprehend',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Berdasarkan pilihan anda, opsi manakah yang benar dibawah ini?'),
        ),
    ]
