# Generated by Django 2.2.4 on 2020-09-25 04:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_attention_check', '0002_auto_20200824_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Ans_one',
            field=otree.db.models.BooleanField(choices=[[False, 'Jakarta'], [False, 'Kucing'], [True, 'Joko Widodo'], [False, 'Maynila Mahathir bin Mohamad']], null=True, verbose_name='請根據您聽到的問題，選出最適合的答案'),
        ),
    ]
