# Generated by Django 2.2.4 on 2020-09-25 03:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_pretest', '0002_auto_20200824_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sound_check',
            field=otree.db.models.BooleanField(choices=[[False, '45'], [False, '21'], [True, '25'], [False, '46']], null=True, verbose_name='Mohon pilih angka yang anda dengarkan dari audio di atas.'),
        ),
    ]
