# Generated by Django 2.2.4 on 2020-08-19 16:25

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp1_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Exp1_survey_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp1_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Exp1_survey_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('gender', otree.db.models.StringField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita'), ('Tidak ada yang di atas', 'Tidak ada yang di atas')], max_length=10000, null=True, verbose_name='1.Apa jenis kelamin anda')),
                ('bloodgroup', otree.db.models.StringField(choices=[('Tipe A', 'Tipe A'), ('Tipe B', 'Tipe B'), ('Tipe AB', 'Tipe AB'), ('Tipe O', 'Tipe O'), ('Tidak tahu', 'Tidak tahu'), ('Tidak ada yang di atas', 'Tidak ada yang di atas')], max_length=10000, null=True, verbose_name='2.Apa golongan darah anda')),
                ('education', otree.db.models.StringField(choices=[('SD', 'SD'), ('SMTP', 'SMTP'), ('SMTA', 'SMTA'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10000, null=True, verbose_name='3.Apa tingkat pendidikan Anda')),
                ('age', otree.db.models.StringField(max_length=10000, null=True, verbose_name='4.Berapa usia anda? (CE)')),
                ('first_language', otree.db.models.StringField(choices=[('Bahasa Indonesia', 'Bahasa Indonesia'), ('Jawa', 'Jawa'), ('Sunda', 'Sunda'), ('Madura', 'Madura'), ('Bugis', 'Bugis'), ('Inggris', 'Inggris'), ('Cina, Taiwan,Hakka, Hokkien, Kanton...', 'Cina, Taiwan,Hakka, Hokkien, Kanton...'), ('Lain', 'Lain')], max_length=10000, null=True, verbose_name='5.Bahasa apa yang paling sering anda gunakan? (Bahasa yang paling nyaman untuk kalian gunakan?')),
                ('second_language', otree.db.models.StringField(choices=[('Bahasa Indonesia', 'Bahasa Indonesia'), ('Jawa', 'Jawa'), ('Sunda', 'Sunda'), ('Madura', 'Madura'), ('Bugis', 'Bugis'), ('Inggris', 'Inggris'), ('Cina, Taiwan,Hakka, Hokkien, Kanton...', 'Cina, Taiwan,Hakka, Hokkien, Kanton...'), ('Lain', 'Lain')], max_length=10000, null=True, verbose_name='6.Selain bahasa Indonesia bahasa ibu Anda, apakah Anda bisa berbicara bahasa lain dengan lancar?')),
                ('guess', otree.db.models.LongStringField(null=True, verbose_name='7.Menurut anda, apakah tujuan eksperimen ini?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp1_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp1_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp1_survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp1_survey.Subsession')),
            ],
            options={
                'db_table': 'Exp1_survey_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp1_survey.Subsession'),
        ),
    ]
