# Generated by Django 2.2.4 on 2020-09-15 07:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='1.Please enter you name.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='5.Berapa usia anda?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bloodgroup',
            field=otree.db.models.StringField(choices=[('Tipe A', 'Tipe A'), ('Tipe B', 'Tipe B'), ('Tipe AB', 'Tipe AB'), ('Tipe O', 'Tipe O'), ('Tidak tahu', 'Tidak tahu'), ('Tidak ada yang di atas', 'Tidak ada yang di atas')], max_length=10000, null=True, verbose_name='3.Apa golongan darah anda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='education',
            field=otree.db.models.StringField(choices=[('SD', 'SD'), ('SMTP', 'SMTP'), ('SMTA', 'SMTA'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10000, null=True, verbose_name='4.Apa tingkat pendidikan Anda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_language',
            field=otree.db.models.StringField(choices=[('Bahasa Indonesia', 'Bahasa Indonesia'), ('Jawa', 'Jawa'), ('Sunda', 'Sunda'), ('Madura', 'Madura'), ('Bugis', 'Bugis'), ('Inggris', 'Inggris'), ('Cina, Taiwan,Hakka, Hokkien, Kanton...', 'Cina, Taiwan,Hakka, Hokkien, Kanton...'), ('Lain', 'Lain')], max_length=10000, null=True, verbose_name='6.Bahasa apa yang paling sering anda gunakan? (Bahasa yang paling nyaman untuk kalian gunakan?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita'), ('Tidak ada yang di atas', 'Tidak ada yang di atas')], max_length=10000, null=True, verbose_name='2.Apa jenis kelamin anda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess',
            field=otree.db.models.LongStringField(null=True, verbose_name='8.Menurut anda, apakah tujuan eksperimen ini?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='second_language',
            field=otree.db.models.StringField(choices=[('Bahasa Indonesia', 'Bahasa Indonesia'), ('Jawa', 'Jawa'), ('Sunda', 'Sunda'), ('Madura', 'Madura'), ('Bugis', 'Bugis'), ('Inggris', 'Inggris'), ('Cina, Taiwan,Hakka, Hokkien, Kanton...', 'Cina, Taiwan,Hakka, Hokkien, Kanton...'), ('Lain', 'Lain')], max_length=10000, null=True, verbose_name='7.Selain bahasa Indonesia bahasa ibu Anda, apakah Anda bisa berbicara bahasa lain dengan lancar?'),
        ),
    ]
